// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package CrashReportFlatbuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppLoadLogV3 struct {
	_tab flatbuffers.Table
}

func GetRootAsAppLoadLogV3(buf []byte, offset flatbuffers.UOffsetT) *AppLoadLogV3 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppLoadLogV3{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AppLoadLogV3) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppLoadLogV3) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppLoadLogV3) Model() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) Os() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) OsVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) CrashSDKVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) AppVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) PackageName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) UserKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) GameCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) Geo() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) City() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) ReportDatetime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppLoadLogV3) MutateReportDatetime(n int64) bool {
	return rcv._tab.MutateInt64Slot(26, n)
}

func (rcv *AppLoadLogV3) MemoryWarning() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) Carrier() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) SessionKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) Emulator() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AppLoadLogV3) MutateEmulator(n bool) bool {
	return rcv._tab.MutateBoolSlot(34, n)
}

func (rcv *AppLoadLogV3) NetworkKind() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) VendorUserKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppLoadLogV3) VendorDeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AppLoadLogV3Start(builder *flatbuffers.Builder) {
	builder.StartObject(19)
}
func AppLoadLogV3AddModel(builder *flatbuffers.Builder, model flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(model), 0)
}
func AppLoadLogV3AddOs(builder *flatbuffers.Builder, os flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(os), 0)
}
func AppLoadLogV3AddOsVersion(builder *flatbuffers.Builder, osVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(osVersion), 0)
}
func AppLoadLogV3AddCrashSDKVersion(builder *flatbuffers.Builder, crashSDKVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(crashSDKVersion), 0)
}
func AppLoadLogV3AddAppVersion(builder *flatbuffers.Builder, appVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(appVersion), 0)
}
func AppLoadLogV3AddPackageName(builder *flatbuffers.Builder, packageName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(packageName), 0)
}
func AppLoadLogV3AddUserKey(builder *flatbuffers.Builder, userKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(userKey), 0)
}
func AppLoadLogV3AddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(deviceId), 0)
}
func AppLoadLogV3AddGameCode(builder *flatbuffers.Builder, gameCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(gameCode), 0)
}
func AppLoadLogV3AddGeo(builder *flatbuffers.Builder, geo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(geo), 0)
}
func AppLoadLogV3AddCity(builder *flatbuffers.Builder, city flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(city), 0)
}
func AppLoadLogV3AddReportDatetime(builder *flatbuffers.Builder, reportDatetime int64) {
	builder.PrependInt64Slot(11, reportDatetime, 0)
}
func AppLoadLogV3AddMemoryWarning(builder *flatbuffers.Builder, memoryWarning flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(memoryWarning), 0)
}
func AppLoadLogV3AddCarrier(builder *flatbuffers.Builder, carrier flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(carrier), 0)
}
func AppLoadLogV3AddSessionKey(builder *flatbuffers.Builder, sessionKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(sessionKey), 0)
}
func AppLoadLogV3AddEmulator(builder *flatbuffers.Builder, emulator bool) {
	builder.PrependBoolSlot(15, emulator, false)
}
func AppLoadLogV3AddNetworkKind(builder *flatbuffers.Builder, networkKind flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(16, flatbuffers.UOffsetT(networkKind), 0)
}
func AppLoadLogV3AddVendorUserKey(builder *flatbuffers.Builder, vendorUserKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(17, flatbuffers.UOffsetT(vendorUserKey), 0)
}
func AppLoadLogV3AddVendorDeviceId(builder *flatbuffers.Builder, vendorDeviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(18, flatbuffers.UOffsetT(vendorDeviceId), 0)
}
func AppLoadLogV3End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
